name: flutter_weather
description: Weather

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-178.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_strategy: ^0.2.0
  json_annotation: ^4.3.0
  http: ^0.13.4
  provider: ^6.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  collection: ^1.15.0
  google_maps_flutter: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
